### ISSUE TITLE
Force fastboot mode

### ISSUE THREAD

**Issue by Jonichka** [Biktorgj/quectel_lk#1]
Hello, thanks for your work on this.

I may have fiddle where i shouldn't. I tried to restore the stock modem by flashing system, recoveryfs, boot, recovery and keeping the  unlocked bootloader in aboot. However the modem is not working properly now. 

You mention that with the unlocked bootloader we can get the modem in fastboot by reseting via gpio pin. Please, can you give me(or the readme) with more detailled instruction to get the modem into fastboot mode or maybe i have to short the test point ?

Best regards
J

**Comment by Biktorgj** [comment]
Sure thing, what distro are you using? and can you access the modem through adb?

**Comment by Jonichka** [comment]
Thank you, I'm using openSUSE with plasma mobile or eventually mobian with phosh, I can't access it with adb and minicom doesnt seems too work neither. What i tried :
When i power the phone the modem appear with lsusb as Quetel wireless lte modem
when i launched eg25manager manually i get "unable to open GPIO chip 1c20800.pinctrl" and  "status is low, modem already powered"
When i try ofonoctl online, it say modem not powered, trying to power on the modem and then operation failed
Then i ran fastboot oem stay to got "waiting for device" --> and then switch the modem hardware switch off and on, but the modem doesn't come back, not even listed with lsusb



I'm not sure if its useful info but that the best, i have, i could access the log as well but i don't know which one would be useful

**Comment by Biktorgj** [comment]
Don't know which kernel config does openSUSE use, so try this first from Mobian which does have the SYSFS_GPIO kernel config enabled:

1. Download this script: https://raw.githubusercontent.com/Biktorgj/pinephone_modem_sdk/hardknott/tools/helpers/gotofastboot
2. On mobian, as root, when the phone has already booted, run: `systemctl stop eg25-manager & killall -9 eg25manager`
3. After you stop and kill eg25-manager (eg25manager tries to shut down the modem when you stop it and we don't really wan't that, that's why I need you to kill it), run `lsusb` to make sure the modem still shows up, then run the `gotofastboot` script. If you don't see any errors on the script, run `fastboot devices` and check if the modem is in fastboot mode. If it is, flash the original bootloader

Let me know if this works for you!

**Comment by Jonichka** [comment]
Great thank you a lot, awesome it worked fine ! 

I just had to launch fastboot devices or fastboot oem stay within 2 seconds to get is to stay and i could flash back the opensource modem, it is working again thanks a lot.

I will try to flash the stock modem back later to see where the problem was when i did it the first time.

**Comment by Biktorgj** [comment]
It was probably my fault. I removed most if not all of the hacks from Quectel in the bootloader, and there's one, that added the modem partition to the kernel command line, that might be needed in stock. So, if you're going stock, restore everything, even the bootloader and you should be fine.

**Comment by Jonichka** [comment]
Oh, okay, i still will try and see. But if it doesn't work, maybe i will keep the open source modem, I don't like messing too often with the boot loader :D
